# Generated by Django 2.1.5 on 2021-11-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_auto_20211116_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Project_img',
            field=models.CharField(default='bla', max_length=255),
        ),
    ]
