# Generated by Django 2.1.5 on 2021-11-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_project_project_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Project_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
