# Generated by Django 2.1.5 on 2021-11-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_auto_20211123_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Project_desc',
            field=models.TextField(max_length=255),
        ),
    ]
