# Generated by Django 2.1.5 on 2021-11-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0005_auto_20211123_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Project_name',
            field=models.TextField(max_length=255),
        ),
    ]
