# Generated by Django 3.2.9 on 2021-12-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0007_alter_project_project_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Skills',
            field=models.TextField(default='SOME STRING', max_length=140),
        ),
    ]
