# Generated by Django 3.2.9 on 2022-07-11 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0010_rename_no_project_project_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Project_no',
        ),
    ]
