# Generated by Django 3.2.9 on 2022-07-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0011_remove_project_project_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Project_no',
            field=models.TextField(default='SOME STRING', max_length=140),
        ),
    ]
